# Generated by Django 5.2.1 on 2025-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
